### login
POST http://127.0.0.1:8000/students/login HTTP/1.1
Content-Type: application/json

{
  "sid":123123,
  "pw":"1234"
}

### logout
GET http://127.0.0.1:8000/students/logout HTTP/1.1
Content-Type: application/json

####

### 회원가입 
POST http://127.0.0.1:8000/students/join HTTP/1.1
Content-Type: application/json

{
  "sid":123123,
  "pw":"1234",
  "name":"이름",
  "phone":"010010"
}

### 회원 id로 조회
GET http://127.0.0.1:8000/students/123123 HTTP/1.1
Content-Type: application/json


### 회원 정보 수정
PUT http://127.0.0.1:8000/students/123123 HTTP/1.1
Content-Type: application/json

{
  "pw":"1234",
  "name":"새로운이름",
  "phone":"010010"
}

### 회원 탈퇴
DELETE http://127.0.0.1:8000/students/123123 HTTP/1.1
